name: 1.0.3$(Rev:.r)

variables:
  - group: secrets
  - name: buildConfiguration
    value: Release

resources:
  repositories:
  - repository: self
    clean: true

  containers:
  - container: es7
    image: gigi81/elasticsearch-windows:7.2.0-windowsservercore-1809
    ports:
    - 30007:9200

pool:
  name: Hosted Windows 2019 with VS2019
  demands:
  - msbuild
  - visualstudio

services:
  es7: es7

steps:
- checkout: self
  submodules: true

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '>=4.3.0'

- task: BatchScript@1
  displayName: 'Build'
  inputs:
    filename: build.bat
    
- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*.Tests*.dll
     !**\*TestAdapter.dll
     !**\obj\**
- powershell: .\deploy.ps1
  displayName: 'Deploy'
  env:
    powershellgallery_apikey: $(powershellgallery_apikey)

- powershell: .\generate-doc.ps1
  displayName: 'Generate documentation'